---
title: Workshop on the Endemic-Epidemic framework for infectious disease modelling
format: html
---

Host: [Centre for Mathematical Modelling of Infectious Diseases](https://www.lshtm.ac.uk/research/centres/centre-mathematical-modelling-infectious-diseases) at the [London School of Hygiene & Tropical Medicine](https://www.lshtm.ac.uk)

## Background

Spatio-temporal models are used extensively to describe infectious disease dynamics while accounting for spatial heterogeneity in transmission risk. The Endemic-Epidemic modelling framework is a class of spatio-temporal models used for analysing subnational case count data implemented in the R package surveillance. It is characterised by its flexibility and ease of use, and it can easily integrate various data streams. It has been used to analyse outbreak dynamics in a wide range of settings, and applied to various diseases (including COVID-19, dengue, measles, and foot and mouth disease). This day-long workshop will provide an overview of the objectives and scope of Endemic-Epidemic models through a hands-on tutorial, followed by several short presentations and discussion on recent applications and future extensions of the framework.

## Organisers

-   Alexis Robert
-   Emily Nightingale
-   Lloyd Chapman
-   Sebastian Funk

## Introduction, tutorial and summary

-   Johannes Bracher
-   Leonhard Held
-   Maria Bekker-Nielsen Dunbar
-   Sebastian Meyer

